// Íconos pixel del menú del celular (12x12, a color, dibujados a mano como los del HUD).
// Cada letra es un color de `ICON_INK`; "." es transparente.

export const ICON_INK: Record<string, string> = {
  k: "#2a1a1a",
  w: "#fdf0c8",
  y: "#ffcf4a",
  o: "#e0923e",
  r: "#d93a2b",
  g: "#5ea247",
  G: "#8cc653",
  b: "#5d93cf",
  l: "#bfe3ff",
  s: "#9a95a0",
  S: "#d8d4dc",
  n: "#b3571a",
  p: "#ff8fb8",
};

export type PhoneAppId = "mensajes" | "contactos" | "camara" | "culebrita" | "tonos" | "temas" | "reloj" | "calculadora" | "info";

export const APP_ICONS: Record<PhoneAppId, string[]> = {
  mensajes: [
    "............",
    "............",
    "kkkkkkkkkkkk",
    "kkwwwwwwwwkk",
    "kwkwwwwwwkwk",
    "kwwkwwwwkwwk",
    "kwwwkwwkwwwk",
    "kwwwwkkwwwwk",
    "kwwwwwwwwrrk",
    "kwwwwwwwwrrk",
    "kkkkkkkkkkkk",
    "............",
  ],
  contactos: [
    "....kkkk....",
    "...kooook...",
    "..kooooook..",
    "..kokookok..",
    "..kooooook..",
    "...kooook...",
    "....kkkk....",
    "..kkkkkkkk..",
    ".kbbbbbbbbk.",
    "kbbbbwwbbbbk",
    "kbbbbwwbbbbk",
    "kkkkkkkkkkkk",
  ],
  camara: [
    "............",
    "..kkkk......",
    "kkkssskkkkkk",
    "ksssssssyyyk",
    "kssskkkksssk",
    "kssklbbbkssk",
    "ksskbbbbkssk",
    "ksskbbbbkssk",
    "kssskkkksssk",
    "kssssssssssk",
    "kkkkkkkkkkkk",
    "............",
  ],
  culebrita: [
    "............",
    "..kkkkkkk...",
    ".kGGGGGGGk..",
    ".kGkkkkkGGk.",
    ".kGk...kkk..",
    ".kGGkkk.....",
    "..kGGGGGkk..",
    "...kkkkkGGk.",
    ".kk....kGGk.",
    "kGkkkkkkGGk.",
    "kGGGGGGGGk..",
    ".kkkkkkkk.r.",
  ],
  tonos: [
    "....kkkkkkkk",
    "....kyyyyyyk",
    "....kykkkkyk",
    "....kyk..kyk",
    "....kyk..kyk",
    "....kyk..kyk",
    "..kkkyk.kkyk",
    ".kyyyyk.kyyk",
    "kyyyyyk.kyyk",
    "kyyyyk.kyyyk",
    ".kkkk..kyyk.",
    ".......kkk..",
  ],
  temas: [
    ".kkkkkkkk...",
    "kpppppppkk..",
    "kpwwpppppk..",
    "kpwppppppk..",
    "kpppppppppk.",
    ".kkkkkkkkkk.",
    "......kk....",
    ".....kook...",
    ".....kook...",
    ".....kook...",
    ".....knnk...",
    "......kk....",
  ],
  reloj: [
    "...kkkkkk...",
    "..kwwwwwwk..",
    ".kwwwkwwwwk.",
    "kwwwwkwwwwwk",
    "kwwwwkwwwwwk",
    "kwwwwkkkkwwk",
    "kwwwwwwwwwwk",
    "kwwwwwwwwwwk",
    ".kwwwwwwwwk.",
    "..kwwwwwwk..",
    "...kkkkkk...",
    "..kk....kk..",
  ],
  calculadora: [
    ".kkkkkkkkkk.",
    ".kGGGGGGGGk.",
    ".kGkGGkGkGk.",
    ".kGGGGGGGGk.",
    ".kkkkkkkkkk.",
    ".kwkwkwkokk.",
    ".kkkkkkkkkk.",
    ".kwkwkwkokk.",
    ".kkkkkkkkkk.",
    ".kwkwkwkrkk.",
    ".kkkkkkkkkk.",
    "............",
  ],
  info: [
    "...kkkkkk...",
    "..kbbbbbbk..",
    ".kbbbwwbbbk.",
    "kbbbbwwbbbbk",
    "kbbbbbbbbbbk",
    "kbbbwwwbbbbk",
    "kbbbbwwbbbbk",
    "kbbbbwwbbbbk",
    ".kbbbwwbbbk.",
    "..kbwwwwbk..",
    "...kkkkkk...",
    "............",
  ],
};
