// El Megabús por dentro dibujado a mano (docs/arte/estandar-arte.md): la barra con timbre, la cabina del
// conductor y el plato del fuelle, en grillas de letras. Leyenda común: los dígitos 0..6 son el verde lima
// de la carrocería; a..e el caucho negro; g..l el gris del metal y del fuelle; V..Z el amarillo de las
// barras; P..T el vidrio polarizado (p, q, r, t, el mismo vidrio dejando ver detrás); A..F el rojo del
// timbre y del extintor; L..N el ámbar de los LED; m, n la pantallita azul; u..w el crema de las etiquetas.
// Los contornos son cálidos y del material: `o` del negro y el gris, `O` del lima, `U` del amarillo, `H`
// del rojo; `s` es la sombra en el piso. Cada grilla trae dónde queda el origen del mueble.
import { BLACK, GREY, HANDRAIL, LED, LIME, TINT } from "./bus-colores";
import { edgeOf, gridSprite, groundShadow, rampLegend, type Legend } from "./grilla";
import { C, mix } from "./palette";
import { alpha, at, type Sprite } from "./pixel";

function busLegend(): Legend {
  return {
    ...rampLegend(LIME, "0123456"),
    ...rampLegend(BLACK, "abcde"),
    ...rampLegend(GREY, "ghijkl"),
    ...rampLegend(HANDRAIL, "VWXYZ"),
    ...rampLegend(TINT, "PQRST"),
    p: alpha(at(TINT, 0), 0.7),
    q: alpha(at(TINT, 1), 0.55),
    r: alpha(at(TINT, 3), 0.6),
    t: alpha(mix(at(TINT, 4), at(C.cream, 4), 0.35), 0.6),
    ...rampLegend(C.rug, "ABCDEF"),
    L: at(LED, 2),
    M: at(LED, 3),
    N: at(LED, 4),
    m: at(C.screen, 3),
    n: at(C.screen, 4),
    u: at(C.cream, 2),
    v: at(C.cream, 4),
    w: at(C.cream, 5),
    o: edgeOf(GREY, 0.55),
    O: edgeOf(LIME, 0.5),
    U: edgeOf(HANDRAIL, 0.45),
    H: edgeOf(C.rug, 0.45),
    s: groundShadow(0.3),
  };
}

type Grid = { rows: readonly string[]; ox: number; oy: number };
const sprite = (g: Grid): Sprite => gridSprite(g.rows, busLegend(), g.ox, g.oy);

// <barra>
const BARRA: Grid = {
  ox: 11,
  oy: 47,
  rows: [
    ".......oooooooo.......",
    "......oklkkjjiho......",
    "......ojjjiiihgo......",
    ".......oUYZXWUo.......",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYwXWU........",
    "........UYwXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    ".......okllkjho.......",
    "........UYZXWooooo....",
    "........UYZXWollllko..",
    "........UYZXWokkkkkjo.",
    "........UYZXWojjjjjjho",
    "........UYZXWojiEDijho",
    "........UYZXWojEFDCjho",
    "........UYZXWojDDCBjho",
    "........UYZXWojiCBijho",
    "........UYZXWojjjjjjho",
    "........UYZXWojwvvujho",
    "........UYZXWoiiiiiiho",
    "........UYZXWUoooooooo",
    ".......okllkjho.......",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "........UYZXWU........",
    "......ooUYZXWUoo......",
    ".....okllUYXWUjho.....",
    "....oklkkjVVWjihho....",
    "....ojhjjiiiiihggo....",
    "....oiihhhhhgggggossss",
    ".....ohhggggggggosssss",
    "......oooooooooossss..",
    ".........sssssssss....",
  ],
};
// </barra>

// <cabina>
const CABINA: Grid = {
  ox: 77,
  oy: 32,
  rows: [
    "..........................................................................................................OO..",
    "............................................................................UU...........................O55O.",
    "..........................................................................UUYYU.........................O4553O",
    "........................................................................UUZZZZXU........................O4433O",
    "......................................................................UUZZZZXXYU........................O4433O",
    "....................................................................UUZZZZXXYY3O........................O4433O",
    "..................................................................UUZZZZXXYYqq3O........................O4433O",
    "................................................................UUZZZZXXYYtqqq3O........................O4433O",
    "..............................................................UUZZZZXXYYqttqqq3O........................O4433O",
    "............................................................UUZZkkkkYYqqqtqqqq3O........................O4433O",
    "..........................................................UUZZkkkkkkkqqqtqqqqq3O........................O4433O",
    "........................................................UUZZkkkkkjjkkqqtqqqqqq3O.......................oT4433O",
    "......................................................UUZZkkkkkjjjjkkqttqqqqqq3O.......................oq4433O",
    "....................................................UUZZZZiikjjjjjjkk444qqqqqq3O......................oTq4433O",
    "..................................................UUZZZZXXiitjjjjjjhh444qqqqqq3O.....................oTqq4433O",
    "................................................UUZZZZXXYYiitjjjjhh444333qqqqt3O.....................oTqq4433O",
    "..............................................UUZZZZXXYYqqiiqjjhgg4433kk3qqqtq3O....................oTqqt4433O",
    "............................................UUZZZZXXYY3qqqii4ghg4433jjkk3qqttq3O....................oqqtq4433O",
    "..........................................UUZZZZXXYYqq3qqt44444433jjjjkk3qqtqq3O...................oTqtqq4433O",
    "........................................UUZZZZXXYYqqqq3q44444433jjjjiikk3qtqqq5O...................oqtqqq4433O",
    ".......................................UZZZZXXYYqqqqqq44444433jjjjiijjkk3tqq552O..................oTtqrqq4433O",
    ".......................................UXXXXYYtqqqqqqq334433jjjjiijjjjkk3t55442O.................oTttrqqq4433O",
    ".......................................UXXYYqttqqqqqqqii3qhhjjiijjjjjjkk3544442O.................oTtrqqqq4433O",
    ".......................................UXX3qqtqqqqqqqtiii3hhiijjjjjjiikk3444332O................oTtrqqqqq4433O",
    ".......................................UXX3qtqqqqqqqqtiii3hhjjjjjjiijjkk3433332O................otqqqqqqq4433O",
    ".......................................O223tqqqqqqqqtqiii3hhjjjjiijjjjkk3333332O...............oTqqqqqqqq4433O",
    ".......................................O223tqqqqqqqtqqiii3hhjjiijjjjjjkk3333332O...............oqqqqqqqqq4433O",
    ".......................................O223qqqqqqqttqqiii3hhiijjjjjjiikk3333332O..............oTrqqqqqqqq4433O",
    ".......................................O223qqqqqqqtqqqiii3hhjjjjjjiijjkk3333332Ooo...........oTrqqqqqqqqq4433O",
    ".......................................O223qqqqqqtqqqqiii3hhjjjjiijjjjkk333ooooooooo....ooo..oTqqqqqqqqqq4433O",
    ".......................................O223qqqqqtqqqqqiii3hhjjiijjjjjhkkiookkkkkjjooo.oobabooTqqqqqqqqqqt4433O",
    ".......................................O223qqqqttqqqqqiii3hhiijjjjjhhhkkokjo11bboohgoobkkkkabqqqqqqqqqqtt4433O",
    ".......................................O223qqqqtqqqq55iii3hhjjjjjhhhkkkokjojiibcbbohgouvvvukTqqqqqqqqqqtr4433O",
    ".......................................O223qqqtqqq5544iii3hhjjjhhhjjkkjokijjjokjobbijoDaavvuqqqqqqqqqqddqb43bo",
    ".......................................O223qqtqq554444iii3hcchhhjjjjjjiojiiiikllkiiigovvvvbTqqqqqqqqdddabbbbbo",
    ".......................................O223qtt55444433iii3bccccijjjjjjjohojjjojho66hgouubaTqqqqqqdddaabbbbb55O",
    "......................................UUZZZZ5544443333iii3bbbccccijjjjjjohgoboho55ogoabaaaTqqqdddaaabbbbb5544O",
    "....................................UUZZZZWW444433333343i3jjbbbccccijjjjjoohhhhhhgoobaaaaTqqdddaabbbbbb554444O",
    "..................................UUZZZZWWWW44333333334333iijjbbbaajiijjbuDooooooobaaaaaadddaaqbbbbbb55444444O",
    "................................UUZZZZWWWWW2333333333343hh33iijjbajjjjbahuvvaavubaaaaaadddaaqbbbbbb5544444444O",
    "..............................UUZZZZWWWWYWW2333333333343hhhh33iijjjjdbaahuuvvvbaaaaadddaaqqbbbbbb5544444jj444O",
    "............................UUZZZZWWWWUZYWW2333333333333hhhhhh33iijjccdbahhhbaaaaadddaaTqbbbbbb5544444jjwj444O",
    "..........................UUZZZZWWWWUUUZYWW2333333333311bbhhhhhh33iiccccdbbaaaadddaaiiibbbbbb5544444jjvwwj443O",
    "........................UUZZZZWWWWUU..UZYWW23333333311bbbcbbhhhhhh3hccccccaaaaddaaiiibbbbbb5544444jjvvvwjj333O",
    "......................UUZZZZWWWWUU....UZYWW233333311bbbcbbbbbchhhhihiiccccaaaaaiiiibbbbbb554444444jvvvjj33333O",
    "....................UUZZZZWWWWUU......UZYWW2333311bbbcbbbbbcbbbbihiiiiiiccaaDaiiibbbbbb55444444444jvjj33333ddo",
    "..................UUZZZZWWWWUU........UZYWW23311bbbcbbbbbcbbbb44iiiiiiiihiiiiiXbbbbbb5544444444444jj33333ddbbo",
    "................UUZZZZWWWWUU..........UZYWW211bbbcbbbbbcbbbbbc4444iiiihiiXaiibbbbbb55444444444444433333ddbbbao",
    "..............UUZZZZWWWWUU............UZYWW1bbbcbbbbbcbbbbbcbb224444hi5aiiibbbbbb55444444444444433333ddbbbaao.",
    "............UUZZZZWWWWWWU.............UZYWWbbcbbbbbcHHHbbcbbbbdc224444iiDahbbbb55444444444444433333ddbbbaaoo..",
    "..........UUZZZZWWWWZYWWU.............UZYWWXbbbbbcbokjhobbbbbcdccc224444hh2bb55444444444444433333ddbbbaaoo....",
    "........UUZZZZWWWWUUZYWWU.............sZYWWaXabcbbbbohoabbbcbbdccccc224422b55444444444444433333ddbbbaaoo......",
    "......UUZZZZWWWWUU.UZYWWU.............sZYWWsaXXabbbHCCHaocbbbbdcaacccc222b5444444444444433333ddbbbaaoo........",
    "....UUZZZZWWWWUU...UZYWWU.............UZYWWsssaXaXHEDDCBHbbbbcdcccaaccccbb44444444444433333ddbbbaaoo..........",
    "..UUZZZZWWWWUU.....UZYWWU..............UYWssssssXaHFEDCBHbbcbbdcaaccaaccb5444444444433333ddbbbaaoo............",
    ".UZZZZWWWWUU.......UZYWWU...............UU..ssssssHFEDCBHcbbbbdcccaacccb544444444433333ddbbbaaoo..............",
    "UYZZWWWWUU.........UZYWWU.....................ssssHEvvvBHbbbbcdcaaccaab54444444433333ddbbbaaoo................",
    "UXYWWWUU...........UZYWWU.......................ssHEuuuBHXbcbbdcccaaccb544444433333ddbbbaaoo..................",
    ".UXWWWU............UZYWWU..oooo..................oHEDDCBHaaXbbdcaaccab54444433333ddbbbaaoo....................",
    ".UZYWWU............UZYWWUooijiioo................oHEDDCBHsXaXadcccaab5444433333ddbbbaaoo......................",
    ".UZYWWU............UZYWWoijiijjiio...............oHEDDCBHsssaXdccccbb44433333ddbbbaaoo........................",
    ".UZYWWU............UZYWijiijjiiijjo..............oHEDDCBHsssssdccccb5433333ddbbbaaoo..........................",
    ".UZYWWU............UZijiijjiiijjiiio.............oHDCCBAHosssssscbb533333ddbbbaaoo............................",
    ".UZYWWU..........ooijiijjiiijjiiighho.............oHHHHHo...sssbbb53333ddbbbaaoo..............................",
    ".UZYWWU........ooijiijjiiijjiiighhhggo.............ooooo...oobbb55333ddbbbaaoo................................",
    ".UZYWWU......ooijiijjiiijjiiighhhggggo...................oobbb55333ddbbbaaoo..................................",
    ".UZYWWU....ooijiijjiiijjiiighhhggggghho................oobbb55333ddbbbaaoo....................................",
    ".UZYWWU..ooijiijjiiijjiiighhhggggghhhho..............oobbb55333ddbbbaaoo......................................",
    ".UZYWWU.ojZZZZjiiijjiiighhhggggghhhhhho............oobbb55333ddbbbaaoo........................................",
    ".UZYWWU.UZZjiZXXjjiiighhhggggghhhhhhhho..........oobbb55333ddbbbaaoo..........................................",
    ".UZYWWUUZjjjiiiXXiighhhggggghhhhhhhhoo.........oobbb55333ddbbbaaoo............................................",
    ".UZYWWUUZjjjiiiiiXhhhggggghhhhhhhhoo.........oobbb55333ddbbbaaoo..............................................",
    ".UZYWWUojjjjiiiiihXggggghhhhhhhhoo.........oobbb55333ddbbbaaoo................................................",
    "..UUUU.ojjjjiiiiihXggghhhhhhhhoo.........oobbb55333ddbbbaaoo..................................................",
    "..ssss.ojjjjiiiiihhXhhhhhhhhoo.........oobbb55333ddbbbaaoo....................................................",
    "..sssssshhjjiiiiihhXhhhhhhoo.........oobbb55333ddbbbaaoo......................................................",
    "....sssssshhiiiiihhhXhhhoo.........oobbb55333ddbbbaaoo........................................................",
    "......sssssshhiiihhhXhoo.........oobbb55333ddbbbaaoo..........................................................",
    "........sssssshhihhhho.........oobbb55333ddbbbaaoo............................................................",
    "..........sssssshhhhho.......oobbb55333ddbbbaaoo..............................................................",
    "............sssssshhho......obbb55333ddbbbaaoo................................................................",
    "..............ssssssho......ob55333ddbbbaaoo..................................................................",
    "................ssssss......O5333ddbbbaaoo....................................................................",
    "..................ssss......O33ddbbbaaoo......................................................................",
    "............................oddbbbaaoo........................................................................",
    "............................obbbaaoo..........................................................................",
    "............................obaaoo............................................................................",
    "............................oaoo..............................................................................",
    ".............................o................................................................................",
  ],
};
// </cabina>

// <plato>
const PLATO: Grid = {
  ox: 81,
  oy: 3,
  rows: [
    "................................................................................oo...............................",
    "..............................................................................ookkoo.............................",
    ".............................................................................okkjjhhoo...........................",
    "............................................................................ogjjhhiikkoo.........................",
    "............................................................................ogggiikkjjhhoo.......................",
    "..........................................................................ookkggggjjhhiikkoo.....................",
    "........................................................................ookkaaaXggggiikkjjhhoo...................",
    "......................................................................ookkXaaaahhhggggjjhhiikkoo.................",
    "....................................................................ookkXXXaajhhhhhhggggiikkjjhhoo...............",
    "..................................................................ookkaXXXXhhgghhhhhhgggggjjhhiikkoo.............",
    "................................................................ookkaaaXXhhhhhhhhhhhhhhhggggiikkjjhhoo...........",
    "..............................................................ookkXaaaahhhhhhhhhhhhhhhhhhhggggjjhhiikkoo.........",
    "............................................................ookkXXXaahhhjjhhhhhhjjhhhhhhjjhhggggiikkjjhhoo.......",
    "..........................................................ookkaXXXXhhhhhhgghhhhhhgghhhhhhgghhhggggjjhhiikkoo.....",
    "........................................................ookkaaaXXhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhggggiikkjjhhoo...",
    "......................................................ookkXaaaahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhggggjjhhiikkoo.",
    "....................................................ookkXXXaaccchhhhjjhhhhhhjjhhhhhhjjhhhhhhjjhhhhhhggggiikkjjhho",
    "..................................................ookkaXXXXjjccccccccgghhhhhhgghhhhhhgghhhhhhgghhhhhhgggggjjhhiio",
    "................................................ookkaaaXXjjjjjjjjjcccccchhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhggggiioo.",
    "..............................................ookkXaaaajjjjjjjjlljjjjjccccchhhhhhhhhhhhhhhhhhhhhhhhhhhhhhXgggo...",
    "............................................ookkXXXaajjjkkjjjjjjkkjjjjjjkcccchhhjjhhhhhhjjhhhhhhjjhhhhhXXXXago...",
    "..........................................ookkaXXXXjjjjjjhhjjjjjjhhjjjjjjhhcccchhgghhhhhhgghhhhhhgghhaaXXXhho....",
    "........................................ookkaaaXXjjjjjjjjjjjjjjjjjjjjjjjllljjcccchhhhhhhhhhhhhhhhhhaaaaXhhoo.....",
    "......................................ookkXaaaakkkhhhhhhkkkkjjjjjjjjjjjjjjjjjjjccchhhhhhhhhhhhhhhXXaaahhoo.......",
    "....................................ookkXXXaahhhjjjjkkjjjjhhhhkkjjjjkkjjjjjjkkjjccchjjhhhhhhjjhXXXXahhoo.........",
    "..................................ookkaXXXXjjhhjjjjjjhhjjjjjjhhhhkkjjhhjjjjjjhhjjccchgghhhhhhaaXXXhhoo...........",
    "................................ookkaaaXXjjjjjjjjjjjjjjjjjjjjjjjjhhkkjjjjjjjjjjjjjccchhhhhhaaaaXhhoo.............",
    "..............................ookkXaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjhhkjjjjjjjjjggjjccchhhXXaaahhoo...............",
    "............................ookkXXXaahjjkkjjjjjjkkjjjjjjkkjjjjjjkkjjhhkjkkjjjjjjkkjjcccXXXXahhoo.................",
    "..........................ookkaXXXXhhjjjjhhjjjjjjhhjjjjjjhhjjjjjjhhjjhhkjhhjjjjjjhhjbaaXXXhhoo...................",
    "........................ookkaaaXXkhhjjjjjjjjjjjjjhhhhhhhhjjjjjjjjjjjjjhhkjjjjjjjjjjaaaaXhhoo.....................",
    "......................ookkXaaaajjkhjjjjjjjjjjjjjhhllllllhhjjjjjjjjjjjjjhkjjjjjjjjXXaaahhoo.......................",
    "....................ookkXXXaakjjjkhjkkjjjjjjkkjhhkkkkkkkkhhjkkjjjjjjkkjhkjjjkkjXXXXahhoo.........................",
    "..................ookkaXXXXjjhhjjkhjjhhjjjjjjhhhhkkkkkkkkhhjjhhjjjjjjhhhkjjjjaaXXXhhoo...........................",
    "................ookkaaaXXjjjjjjjjkhjjjjjjjjjjjjjhhkkkkkkhhjjjjjjjjjjjjjhkjjaaaaXhhoo.............................",
    "..............ookkXaaaajjjjjjjjjjkhhjjjjjjjjjjjjjhhhhhhhhjjjjjjjjjjjjjhhkXXaaahhoo...............................",
    "....oo......ookkXXXaabjjkkjjjjjjkkkhhjjjkkjjjjjjkkjjjjjjkkjjjjjjkkjjjhhXXXXahhoo.................................",
    "..ookkoo..ookkaXXXXaaajjjhhjjjjjjhhkhhjjjhhjjjjjjhhjjjjjjhhjjjjjjhhjhaaXXXhhoo...................................",
    ".okkjjhhookkaaaXXhhhaaajjlljjjjjjjjjkhhjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaXhhoo.....................................",
    "objjhhiikkXaaaahhhhhhaaajjjjjjjjjjjjjkkhhjjjjjjjjjjjjjjjjjjjjjjjjXXaaahhoo.......................................",
    "ojbbiikkjjhhajhhhhhhjjaaajjjkkjjjjjjkkjkkhhjkkjjjjjjkkjjjjjjkkjXXXXahhoo.........................................",
    "ojigbbjjhhiikkghhhhhhggaaajjjhhjjjjjjhhjjjkkhhhhjjjjjhhjjjhhhaaXXXhhoo...........................................",
    "ojighjbbiikkjjhhhhhhhhhhaaajjjjjjjjjjjjjjjjjjjkkkkhhhhhhkkkaaaaXhhoo.............................................",
    ".oighjigbbjjhhiikkhhhhhhhaaaajjgggjjjjjjjjjjjjjjjjjjjjjjjXXaaahhoo...............................................",
    "..oohjighjbbiikkjjhhhhhhjjhaaaajkkjjjjjjkkjjjjjjkkjjjjjXXXXahhoo.................................................",
    "....ooighjigbbjjhhiikkhhhgghhaaaahhjjjjjjhhjjjjjjhhjjaaXXXhhoo...................................................",
    "......oohjighjbbiikkjjhhhhhhhhhaaaaajjjjjggjjjjjjjjaaaaXhhoo.....................................................",
    "........ooighjigbbjjhhiikkhhhhhhhhaaaaaajjjjjjjjjXXaaahhoo.......................................................",
    "..........oohjighjbbiikkjjhhjjhhhhhhjaaaaaaaakjXXXXahhoo.........................................................",
    "............ooighjigbbjjhhiikkghhhhhhgghhhaaaaaXXXhhoo...........................................................",
    "..............oohjighjbbiikkjjhhhhhhhhhhhhhaaaaXhhoo.............................................................",
    "................ooighjigbbjjhhiikkhhhhhhhXXaaahhoo...............................................................",
    "..................oohjighjbbiikkjjhhhhhXXXXahhoo.................................................................",
    "....................ooighjigbbjjhhiihaaXXXhhoo...................................................................",
    "......................oohjighjbbiihaaaaXhhoo.....................................................................",
    "........................ooighjigbUXaaahhoo.......................................................................",
    "..........................oohjighoUohhoo.........................................................................",
    "............................ooigho..oo...........................................................................",
    "..............................ooho...............................................................................",
    "................................o................................................................................",
  ],
};
// </plato>

/** El azul de los preferenciales en los mismos tonos del lima (la concha) y del negro (la tela). */
const BLUE_SHELL: Legend = {
  "0": at(C.blue, 0),
  "1": at(C.blue, 1),
  "2": mix(at(C.blue, 1), at(C.blue, 2), 0.5),
  "3": at(C.blue, 2),
  "4": mix(at(C.blue, 2), at(C.blue, 3), 0.5),
  "5": at(C.blue, 3),
  "6": at(C.blue, 4),
  a: at(C.fabric, 0),
  b: mix(at(C.fabric, 0), at(C.fabric, 1), 0.5),
  c: at(C.fabric, 1),
  d: mix(at(C.fabric, 1), at(C.fabric, 2), 0.5),
  e: at(C.fabric, 2),
};

// <asiento>
const ASIENTO: Grid = {
  ox: 13,
  oy: 26,
  rows: [
    "...........UUU............",
    ".........UUZZZU...........",
    ".......UUZZZXXU...........",
    ".....UUZZZXXXWU...........",
    "...UUZZZXXXYYWUO..........",
    "..UZZZXXXO66YW54O.........",
    ".UYYXXXO66555443O.........",
    ".UYYXO6655544d33O.........",
    ".UYYW655544cdd33O.........",
    ".UYYW5544cccdd33O.........",
    "O455544cccccdd33O.........",
    "O54O4cccccccbb33O.........",
    "O54O3cccccbbdd33O.........",
    "O54O3cccbbccdd33O.........",
    "O54O3cbbccccdd33O.........",
    "O54O3bccccccbb33O.........",
    "O54O3cccccbbdd33O.........",
    "O54O3cccbbccdd33O.........",
    "O54O3cbbccccdd33O.........",
    "O54O3bccccccd333Oo........",
    "O54O3cccccc333ddccoo......",
    "O54O3cccc333bcccccccoo....",
    "O54O3cc333dddbbdddddccoo..",
    "O54O3333bddddddbbddddeebo.",
    "O54533dddbbddddddbbeebbb5O",
    ".O555cccdddbbddddeebbb543O",
    ".O44555ccccccbbeebbb54331O",
    ".O2244555cccdeebbb543311O.",
    "..OO2244555cc5bb543311OO..",
    "....OO22445555543311OO....",
    "......OO2244543311OO......",
    "........oO224311ss........",
    ".......ojjkj21hijjss......",
    "......sijjjjjhhjjjhsss....",
    "....ssssiijjjjjjhhssssss..",
    "..ssssssssiijjhhssssssssss",
    "..ssssssssssihssssssssssss",
    "....ssssssssssssssssssss..",
    "......ssssssssssssssss....",
    "........ssssssssssss......",
    "..........ssssssss........",
    "............ssss..........",
  ],
};
// </asiento>

// <asiento-b>
const ASIENTO_B: Grid = {
  ox: 12,
  oy: 21,
  rows: [
    "...................UUUU..",
    ".................UUZZZXU.",
    "...............UUZZZXXXU.",
    ".............UUZZZXXXUWU.",
    "...........UUZZZXXXUY6WU.",
    "..........UZZZXXXO665555O",
    "..........UYXXXO66555544O",
    "..........UYXO6655554444O",
    "..........UYW65555444244O",
    ".........O6YW55544422244O",
    "........O445554442233244O",
    "........O544444223333244O",
    "........O544442333333244O",
    "........O544445333333244O",
    "........O544445333333244O",
    "......oob544445333333244O",
    "....ooddd544445333333244O",
    "..oobbddd544445333335244O",
    ".occccbbc544445333554444O",
    ".occcdddb544445355444444O",
    "O555cccdd544445544444443O",
    "O44555ccc544444444444331O",
    "O2244555c54444444443311O.",
    ".OO224455544444443311OO..",
    "...OO22445444443311OO....",
    ".....OO2244543311OO......",
    ".......oO224311ss........",
    "......ojjkj21hijjss......",
    ".....sijjjjjhhjjjhsss....",
    "...ssssiijjjjjjhhssssss..",
    ".ssssssssiijjhhssssssssss",
    ".ssssssssssihssssssssssss",
    "...ssssssssssssssssssss..",
    ".....ssssssssssssssss....",
    ".......ssssssssssss......",
    ".........ssssssss........",
    "...........ssss..........",
  ],
};
// </asiento-b>

/**
 * Asiento de pasajero mirando hacia +x (de espaldas, `back`): concha de plástico moldeado verde lima con el
 * cojín negro y sus costuras, o el azul de los preferenciales con su tela; el agarradero amarillo encima.
 */
export function busSeatSprite(back: boolean, blue: boolean): Sprite {
  const l = busLegend();
  const legend: Legend = blue ? { ...l, ...BLUE_SHELL, O: edgeOf(C.blue, 0.5) } : l;
  const g = back ? ASIENTO_B : ASIENTO;
  return gridSprite(g.rows, legend, g.ox, g.oy);
}

/** Barra amarilla de piso a techo con su base atornillada y el timbre rojo de "PARE". */
export const busPoleSprite = (): Sprite => sprite(BARRA);
/** El puesto del conductor al frente del bus: mampara, silla, timón, tablero con relojes y el parabrisas. */
export const busCabinSprite = (): Sprite => sprite(CABINA);
/** El plato giratorio del fuelle con su lámina antideslizante, el aro de caucho y los pliegues alrededor. */
export const busTurntableSprite = (): Sprite => sprite(PLATO);
