// Los trajes completos (el detalle de cada uno está en costumes.ts). Van aparte para que look.ts los
// valide sin importar las recetas. Ojo con el orden: agregar siempre al final.
export const COSTUME_IDS = [
  "oficinista",
  "ejecutivo",
  "programador",
  "chef",
  "barista",
  "crupier",
  "medico",
  "bombero",
  "obrero",
  "granjero",
  "apicultor",
  "jardinero",
  "pescador",
  "marinero",
  "deportista",
  "dj",
  "cine",
  "playa",
  "rockero",
  "artista",
  "pijama",
  "invierno",
  "ruana",
  "smoking",
  "gala",
  "fiesta",
  "realeza",
  "astronauta",
  "pirata",
  "superheroe",
  "mago",
  // Los de los oficios (se desbloquean con el nivel: ver oficios.ts).
  "pescador-lago",
  "lobo-lago",
  "hortelano",
  "maestro-huerta",
  "cocinero",
  "chef-mayor",
  "anfitrion",
  "alma-fiesta",
  "explorador",
  "cartografo",
  // Los de la Noche de brujas.
  "bruja",
  "vampiro",
  "calabaza",
  "esqueleto",
  // Los del Carnaval de Negros y Blancos.
  "comparsa-blanca",
  "arlequin-pastuso",
  "talco-ceniza",
  // El del Año viejo (la ropa amarilla del agüero).
  "ano-nuevo-amarillo",
] as const;
export type CostumeId = (typeof COSTUME_IDS)[number];
