// Los trajes completos (el detalle de cada uno está en costumes.ts). Van aparte para que look.ts los
// valide sin importar las recetas. Ojo con el orden: agregar siempre al final.
export const COSTUME_IDS = [
  "oficinista",
  "ejecutivo",
  "programador",
  "chef",
  "barista",
  "crupier",
  "medico",
  "bombero",
  "obrero",
  "granjero",
  "apicultor",
  "jardinero",
  "pescador",
  "marinero",
  "deportista",
  "dj",
  "cine",
  "playa",
  "rockero",
  "artista",
  "pijama",
  "invierno",
  "ruana",
  "smoking",
  "gala",
  "fiesta",
  "realeza",
  "astronauta",
  "pirata",
  "superheroe",
  "mago",
] as const;
export type CostumeId = (typeof COSTUME_IDS)[number];
